### ISSUE TITLE
Calc.exe not popping

### ISSUE THREAD

**Issue by JohnWoodman** [PorLaCola25/PPID-Spoofing#1]
Hey, so I'm learning about ntcreateuserprocess and trying to use it to pop calc. I came across your github repo and it looks like really good stuff!

I am having a few issues though that is preventing calc from being opened. For the clientId.UniqueProcess, are you assigning it to a remote process ID that already exists? For example, could I start up notepad, get it's process ID and assign that to clientId.UniqueProcess? 

When I try that, in process explorer, it shows that calc.exe process has been created, but its suspended, and doesn't actually run. 

My final issue (which might be the main problem) is that ZwWriteVirtualMemory is returning a non-zero status code 0x8000000D   STATUS_PARTIAL_COPY. Not sure if you know why this issue is happening?

Any help with this would be really appreciated, and again great work!

**Comment by PorLaCola25** [comment]
Hi John, regarding your first issue, yes, clientId.UniqueProcess specified get assigned to an already existing process ID (the process to be used as parent). 

The ZwWriteVirtualMemory issue can be caused by several factor, can you attach a debuger to the suspended calc and actually check if your shellcode is getting written and its protection levels?

With that being said, I must note that this POC is outdated, the shellcode harcoded won't run since it is at reflective loader. It needs structs such as the TIB which doesn't exist at that point in the process. If possible, i would adivse using NtCreateProcessEx for process creation, workflow would go somewhat among this lines:

NtOpenFile -> NtCreateSection & NtOpenProcess(Parent process) -> NtCreateProcessEx -> NtCreateThreadEx

You can find a working example of this https://github.com/PorLaCola25/ProcessDoppelganging

**Comment by JohnWoodman** [comment]
Ah ok, I think I'll just focus on the NtCreateProcessEx method then if that one is more up to date. 

I also have a sort of dumb question. My main goal is to basically write a reverse shell using only direct syscalls. I'm essentially trying to rewrite this code (https://code.sololearn.com/c9QMueL0jHiy/#cpp) using direct syscalls. 

I'm wondering, is it possible to do this without injecting or using any shellcode? My hope is that I can essentially create a "cmd.exe" process, just as you would with CreateProcessA(), but using the direct syscall implementation.

Thanks for all your help so far!

**Comment by PorLaCola25** [comment]
Yes, using the workflow described before you can do it. No injection is done, you would just spawn a new cmd as a child process of a parent process of your choosing.

**Comment by JohnWoodman** [comment]
Awesome, thanks so much! And just one last quick question. Since you're hardcoding the system call numbers, what version of Windows are you using? System call numbers tend to change between versions so just want to make sure I don't need to change the system call numbers in the ASM file.

Thanks again!

**Comment by PorLaCola25** [comment]
Win 10 2004, a complete table of syscalls can be found at https://j00ru.vexillium.org/syscalls/nt/64/
